apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-cleanup-config
  namespace: nextcloud
type: Opaque
stringData:
  DELETION_GRACE_PERIOD: "86400"
  NEXTCLOUD_FILENAME_PATTERN: urn:oid:%d
  AWS_DEFAULT_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_BUCKET:
  AWS_ENDPOINT:
  DATABASE_HOST:
  DATABASE_USER:
  DATABASE_PASSWORD:
  DATABASE_NAME: nextcloud
